### PR TITLE
chore: add renovate config for goimports

### PR DESCRIPTION
**Pull request by frezbo**
Add renovate config for goimports

Ref: https://github.com/aquaproj/aqua-registry/pull/5145

Signed-off-by: Noel Georgi <git@frezbo.dev>

### CODE REVIEW

**Comment by suzuki-shunsuke** [comment]
Thank you for your contribution.

I expect goimports should be updated by this rule.
https://github.com/aquaproj/aqua-renovate-config/blob/f462818c35496b6fa77879d9d0627f98acb9ca89/default.json#L95-L102

But it seems not to work as expected. 🤔 
I'll take a look.

* https://github.com/suzuki-shunsuke/test-renovate/blob/cb29406e4331f857ea20472e05225bd4f98dee1c/aqua.yaml#L8
* https://github.com/suzuki-shunsuke/test-renovate/blob/cb29406e4331f857ea20472e05225bd4f98dee1c/renovate.json#L4

https://github.com/suzuki-shunsuke/test-renovate/issues/106

image

https://app.renovatebot.com/dashboard#github/suzuki-shunsuke/test-renovate/754264919

```json
{
        "packageFile": "aqua.yaml",
        "deps": [
          {
            "depName": "golang.org/x/tools/cmd/goimports",
            "currentValue": "v0.1.10",
            "datasource": "go",
            "replaceString": " name: golang.org/x/tools/cmd/goimports@v0.1.10",
            "depIndex": 0,
            "warnings": [],
            "versioning": "semver",
            "sourceUrl": "https://github.com/golang/tools",
            "updates": []
          }
        ],
        "matchStrings": [
          " +['\"]?(version|ref)['\"]? *: +['\"]?(?<currentValue>[^'\" \\n]+?)['\"]? +# renovate: depName=(?<depName>[^\\n]+)",
          " +['\"]?name['\"]? *: +['\"]?(?<depName>[^\\n]+)*@(?<currentValue>[^'\" \\n]+)['\"]?"
        ],
        "datasourceTemplate": "go"
      }
```

**Comment by suzuki-shunsuke** [comment]
For example, `golang.org/x/tools/gopls` was updated properly.

https://github.com/aquaproj/aqua-registry/pull/5113

So I expect `golang.org/x/tools/cmd/goimports` is also updated.

**Comment by frezbo** [comment]
> But it seems not to work as expected. thinking
> I don't know why Renovate doesn't create a pull request.

That's exactly what I saw too, renovate didn't do a PR (I didn't spend much time figuring it out, thought it was because it had issues with go projects having multiple tags)

**Comment by frezbo** [comment]
closing since we might have a better solution as per discussion in #191

**Pull request closed without merging**
